config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags do 
    member do 
      get '/tags/:id/edit_note', to: 'tags#edit_note', as: 'edit_note'
      patch '/', to: 'tags#update_note', as: 'update_note'
    end
  end
  
  
  root to: "home#index"

end

app/models/add_tag.rb
class AddTag < ApplicationRecord
    belongs_to :tag
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :user
    # has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tags    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
        devise_parameter_sanitizer.permit(:log_in) { |u| u.permit(:name, :email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
        if user_signed_in?
            redirect_to tags_path
        end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search].present?
      @tags = current_user.tags.joins(:user).where("tags.title Like ?", "%"+params[:search]+"%")
    else
      @tags = current_user.tags
    end
  end
 

  def edit
      @tag = current_user.tags.find(params[:id])
  end

  def edit_note
      @tag = current_user.tags.find(params[:id])
  end

  def show
      @tag = current_user.tags.find(params[:id])
  end

  def new
      @tag = current_user.tags.build
  end

  def create
      @user = current_user
      @tag = @user.tags.build(tag_params)
      @tag.save
      respond_to do |format|
        format.js do
          if @tag.valid?
            flash.now[:notice] = "Your tag was successfully created"
          else
            flash.now[:error] = "You tag was not created"
          end
        end
      end
  end
  
  def update_note
    @tag = current_user.tags.find(params[:id])
    @tag.update(tag_params)
    respond_to do |format|
      format.js do
        if @tag.valid?
          flash.now[:notice] = "Your note was successfully updated"
        else
          flash.now[:error] = "You note was not updated"
        end
      end
    end   
  end

  def update
      @tag = current_user.tags.find(params[:id])
      @tag.update(tag_params)
      respond_to do |format|
        format.js do
          if @tag.valid?
            flash.now[:notice] = "Your note was successfully saved"
          else
            flash.now[:error] = "You note was not saved"
          end
        end
      end   
  end

  def destroy
      @tag = current_user.tags.find(params[:id])
      @tag.destroy
      respond_to do |format|
        format.js do
          if @tag.valid?
            flash.now[:notice] = "Your tag was removed successfully "
          else
            flash.now[:error] = "You tag was not removed"
          end
        end
      end  
  end

  private
  def tag_params
      params.require(:tag).permit(:title, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    def ajax_flash(div_id)
        response = ""
        flash_div = ""
    
        flash.each do |name, msg|
          if msg.is_a?(String)
            flash_div = "<div class=\"alert alert-#{name == "notice" ? 'success' : 'error'} ajax_flash\"><a class=\"close\" data-dismiss=\"alert\"></a> <div id=\"flash_#{name == :notice ? 'notice' : 'error'}\">#{h(msg)}</div> </div>"
          end 
        end
    
        response = "$('.ajax_flash').remove();$('#{div_id}').prepend('#{flash_div}');"
        response.html_safe
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myamplenotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
      

    
    </head>

  <body>
      
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>   
        </ul>

        <div class="nav-item">
        
          <% if user_signed_in? %>
            <div class="dropdown">
              <a class="nav-link dropdown-toggle"  id="dropdownMenuLink" data-bs-toggle="dropdown">
                  <%= current_user.email %>
              </a>

              <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </ul>
            </div>
          <% end %>  
              
        </div>  

      </div>
    </div>
  </nav>

  <div id="main" role="main">
     
    <div class="row">
      <div class="span12" id="top-div"> 
      
        <%= yield %>
      </div>
    </div>
     
  </div> 

  </body>
</html>

app/views/tags/_edit_form.html.erb
<%= form_for tag, remote: true do |form| %>
    <%#= form.rich_text_area :content, style: "width: 100%; height: 400px;", class: "shadow p-2 rounded" %>
    <%= form.text_area :content, style: "width: 100%; height: 400px;", class: "shadow p-2 rounded" %>
                <br/>
    <%= form.submit "Save Note",class: "btn btn-outline-primary save-note" %> 
<% end %>

app/views/tags/_edit_note_form.html.erb
  <%= form_for tag, url: update_note_tag_path(@tag), method: :patch, remote: true do |form| %>
  <div class="modal-body">
      <div class="form-group mt-3">
          <h5><%= form.label :title %><h5>
          <%= form.text_field :title, class: "form-control" %>
      </div>
    
      <div>
        <%= form.submit "Update Notes", class: "btn btn-outline-info btn-lg close-modal" %>
        <button type="button" class="btn btn-outline-info btn-lg close-modal" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  <% end %>

app/views/tags/_form.html.erb
<%= form_for tag, remote: true do |form| %>
 <div class="modal-body">
    <div class="form-group mt-3">
        <h5><%= form.label :title %><h5>
        <%= form.text_field :title, class: "form-control" %>
    </div>
   
    <div>
      <%= form.submit "Create Title", class: "btn btn-outline-primary btn-lg close-modal" %>
      <button type="button" class="btn btn-outline-info btn-lg close-modal" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="tagForm_<%= tag.id %>" >
    <div class="row border border-dark rounded shadow p-1 mb-2">
        <div class="col col-10">
           
            <%= link_to edit_tag_path(tag), class: "btn btn-outline-dark active_button #{index == 0 ? 'activated' : ''}", style: "display: block;", remote: true do %>
                <h5><%= tag.title %></h5>
                <i><%= time_ago_in_words(tag.created_at) %> ago by <%= tag.user.email %></i>
                
            <% end %>
                
        </div>
        
        <div class="col col-2 ">
       
            <%= link_to tag, method: :delete, class: "btn btn-outline-danger bi bi-trash-fill mt-1", data: { confirm: 'Are you sure?' }, remote: true  do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            <% end %>
            
            <%= link_to edit_note_tag_path(tag), class: "btn btn-outline-info  mt-2", data: { bs_toggle: "modal", bs_target: "#editTagModal", remote: true } do %>
            <i class="fa-solid fa-file-pen"></i>
            <% end %>
        </div>
    </div>
  </div>      

 

app/views/tags/create.js.erb
$("#CrateNote").append("<%= j render("tag", tag: @tag) %>")
$("#addtag-section").html("<%= j render 'edit_form', tag: @tag %>")
$('#myModal').modal('hide');
<%= ajax_flash('#top-div') %>

app/views/tags/destroy.js.erb
$("#tagForm_<%= @tag.id %>").remove();
$("#addtag-section").html("")
<%= ajax_flash('#top-div') %>

app/views/tags/edit.js.erb
$("#addtag-section").html("<%= j render 'edit_form', tag: @tag %>")

app/views/tags/edit_note.js.erb
$("#EditTagForm").html("<%= j render 'edit_note_form', tag: @tag %>")

app/views/tags/index.html.erb
    <br>
    <br>

    <div class="container">
        <div class="row">
          <div class="col-12">
            <%= link_to "New Note", new_tag_path, class: "btn btn-outline-primary", data: { "bs-target": "#myModal", "bs-toggle": "modal" }, remote: true %>
            <br/>
            <br/>
          </div>
    <!----------------------title------------------>  
           
          <div class="col-4">
            <div id="CrateNote">
              <div id="myDIV">
                
                <% @tags.each_with_index do |tag, index| %>
                  
                    <%= render "tag", tag: tag, index: index %>
                  
                <% end %>
              </div>  
            </div>
          </div>
    <!--------------------Notes------------------>    
         
          <div class="col-8">
            <div id="tagRow_<%= tag.id %>">
              <div id="addtag-section">
               <% if Tag.first.present? %>
                 <%= render "edit_form", tag: Tag.first %>
               <% end %>  
              </div>
            </div>
          </div>
        </div>
    </div>


    <!-- The Modal -->
    <div class="modal" id="myModal">
      <div class="modal-dialog" style="width: 400px;">
        <div class="modal-content">
          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title" data-bs-toggle="modal" data-bs-target="#myModal" >
              <div id="NewTagForm" >
                  
              </div>
            </h4>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="editTagModal" tabindex="-1" aria-labelledby="editTagModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editTagModalLabel">Edit Tag Title</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <div id="EditTagForm">
            
          </div>
        
      </div>
    </div>

    <script>

        // Add active class to the current button (highlight it)
        var header = document.getElementById("myDIV");
        var btns = header.getElementsByClassName("active_button");
        for (var i = 0; i < btns.length; i++) {
          btns[i].addEventListener("click", function() {
           
          var current = document.getElementsByClassName("activated");
          current[0].className = current[0].className.replace("activated", "");
          this.className += "activated";
          });
        }

    </script>
 

    <style> .activated {
        color: #fff;
        background-color: #212529;
        border-color: #212529;
    } 
    </style>





  

app/views/tags/new.js.erb
$("#NewTagForm").html("<%= j render 'form', tag: @tag %>")

app/views/tags/update.js.erb
$("#tagRow_<%= @tag.id %>").append("<%= j render( "edit_form", tag: @tag) %>")
<%= ajax_flash('#top-div') %>

app/views/tags/update_note.js.erb
$("#tagForm_<%= @tag.id %>").html("<%= j render( "tag", tag: @tag) %>");
$('#editTagModal').modal('hide');
<%= ajax_flash('#top-div') %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>